##打包部署的时候将该配置更改为prod

server:
  port: 8082
  tomcat:
    max-threads: 800

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

###################  spring配置  ###################
#spring.http.converters.preferred-json-mapper=fastjson
spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  #是否开启开发者工具（true/false）
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  aop:
    #false为启用jdk默认动态代理,true为cglib动态代理
    proxy-target-class: true
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  ###################  邮件服务配置  ###################
  mail:
    host: smtp.qq.com
    username: enidfdluzt@qq.com
    password: wnsdfsdfsdfbfbjhc
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    ###监控配置 begin###
    druid:
      # WebStatFilter配置，说明请参考Druid Wiki，配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druiduser
        login-password: druidpassword
        allow: 127.0.0.1
    ###监控配置 end###